### ISSUE TITLE
one process function to dispatch on File and Directory

### ISSUE THREAD

**Issue by maltesie** [jonathanBieler/BioRecordsProcessing.jl#11]
Hi @jonathanBieler,

I'm trying to integrate your package into my [RNASeqTools](https://github.com/maltesie/RNASeqTools) and I'm missing some iteration functionality to use the File and Directory structs. If thats OK with you, I would try to implement this and make a PR.

As a second thought: what do you think of having one single process function that dispatches on the File and Directory structs?

Best,
Malte

**Comment by jonathanBieler** [comment]
Hi, PRs are welcome (as long as they have docs & tests). But can you give me an example (from high level API) of what you want to do that currently isn't possible ?

**Comment by maltesie** [comment]
I have a few functions for fastq files processing:

- demultiplexing (dont understand yet if that is possible with your Sinks, since there would be multiple outputs from one input)
- splitting interleaved fastq files (should be possible already)
- running binaries on directories like bwa, minimap or fastp. For those I'd like to use your Directory struct to iterate through the files.

I saw that your Pipelines do dispatch on File and Directory, did not realize this when I wrote the issue, sorry.

**Comment by jonathanBieler** [comment]
For demultiplexing we could add a "dispatch" reader (maybe not the right name), something like this :

```julia
Pipeline(
    DispatchReader(FASTX.FASTA, File(filepath); Noutput = 8, output_prefix = i -> "file_$(i)" ),
    record -> begin
        # figure out which output i we want to write the record to
        return i, record
    end,
    Writer(FASTX.FASTA, dir), # will write to file_$(i)_rest_of_filename
)
```

An alternative (that should work already) would be to directly write from the processing function, the downside is that you have to manage writing by yourself, which bring boilerplate again.

```julia
Pipeline(
    Reader(FASTX.FASTA, File(filepath)),
    record -> begin
        # figure out which output i we want to write the record to and write it
        nothing
    end,
    nothing #need to add support for doing nothing here
)
```

You could give DispatchReader a try, a worry is that as we add more option the number of combinations might go out of hand (it need to work with Buffer, paired reads, ...).

**Comment by jonathanBieler** [comment]
I'm not sure for external tools, maybe something like this :

```julia
p = Pipeline(
    ExternalTool(Directory(dir, "*.fa")),
    file  -> run(`bwa $file`)
    # if no writer is provided => nothing
)
```

It would be good for it to work with collect too (fo

```julia
p = Pipeline(
    ExternalTool(Directory(dir, "*.fa")),
    file  -> # run too and return output
   Collect(String)
)
```

**Comment by maltesie** [comment]
Sorry for not answering this long. I thought about it a bit, having a dispatch reader sounds like a good thing to have in your package, this has some common applications (at least demultiplexing). But for the external tool I think it would be easier to just use your Directory and loop through the files, then use run(). It's more or less the same amount of code, or?

**Comment by jonathanBieler** [comment]
Hey @maltesie, I tried to add support for external tools. Instead a giving a function we can now wrap it in a `ExternalTool` and dispatch on that, and File and Directory can be used as sources directly. I'm not sure what to do with sinks, you can just leave it empty (defaults to nothing) and it will just returns whatever the function returns.

```julia
        p = Pipeline(
            File(bam),
            ExternalTool(filepath ->
                read(`head -1 $filepath`, String)
            ),
        )
        out = run(p)
```

https://github.com/jonathanBieler/BioRecordsProcessing.jl/blob/main/test/test_pipeline.jl#L34

Does that suit your needs ?
